FROM arm32v7/python:3.6-slim

RUN mkdir -p /app/pytel_bot
WORKDIR /app/

COPY requirements.txt .
RUN pip install -r requirements.txt && \
    rm requirements.txt && \
    apt-get update && \
    apt-get install -y procps && \
    apt-get install -y --no-install-recommends libmagickwand-6.q16-3 && \
    apt-get clean && \
    rm -rf /var/lib/apt && \
    rm -rf /var/cache/apt

COPY main.py insultos.txt useless_data.txt insults.txt ./
COPY pytel_bot ./pytel_bot/

CMD python main.py
